// Generated by Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
#ifndef ADOPUTILITY_SWIFT_H
#define ADOPUTILITY_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ADOPUtility",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class ADOPRepeatStopper;

SWIFT_CLASS("_TtC11ADOPUtility15ADOPObjCUtility")
@interface ADOPObjCUtility : NSObject
+ (BOOL)shouldNetworkReqWithCriterion:(id _Nullable)adWeight SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)identifierForAdvertising SWIFT_WARN_UNUSED_RESULT;
+ (ADOPRepeatStopper * _Nonnull)repeatAction:(void (^ _Nonnull)(void))action for:(double)seconds :(ADOPRepeatStopper * _Nullable)shouldStop SWIFT_WARN_UNUSED_RESULT;
+ (void)logger:(NSArray<NSString *> * _Nonnull)stringToPrint;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS("_TtC11ADOPUtility17ADOPRepeatStopper")
@interface ADOPRepeatStopper : NSObject
@property (nonatomic, strong) NSNumber * _Nonnull shouldStop;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol BidmadNativeAdDataInterface;

SWIFT_PROTOCOL("_TtP11ADOPUtility29BIDMADNativeAdCommonInterface_")
@protocol BIDMADNativeAdCommonInterface
@property (nonatomic) BOOL isAdMob;
- (nonnull instancetype)initWith:(NSString * _Nonnull)appid placementId:(NSString * _Nullable)placementId bidmadController:(id _Nonnull)bidmadController isDebug:(BOOL)isDebug isChildDirectedAds:(NSNumber * _Nullable)isChildDirectedAds loadCallback:(void (^ _Nonnull)(id <BidmadNativeAdDataInterface> _Nullable))loadCallback clickCallback:(void (^ _Nonnull)(id <BidmadNativeAdDataInterface> _Nullable))clickCallback;
- (void)remove;
@end

@class UIViewController;
@class UIView;

SWIFT_CLASS("_TtC11ADOPUtility24BidmadAdapterAdEssential")
@interface BidmadAdapterAdEssential : NSObject
@property (nonatomic, strong) id _Nullable bidmadController;
@property (nonatomic, copy) NSString * _Nullable appID;
@property (nonatomic, copy) NSString * _Nullable pubID;
@property (nonatomic, strong) UIViewController * _Nonnull rootVC;
@property (nonatomic, strong) UIView * _Nullable parentView;
@property (nonatomic) BOOL debugMode;
@property (nonatomic, readonly, strong) NSNumber * _Nullable childDirectedTreatment;
@property (nonatomic, readonly, strong) NSNumber * _Nullable isGDPRConsent;
@property (nonatomic, readonly, strong) NSNumber * _Nullable isCCPAConsent;
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
+ (void)ifRespondsPerform:(id _Nonnull)callbackController methodToCall:(NSString * _Nonnull)methodToCall with:(id _Nullable)object1 with:(id _Nullable)object2;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP11ADOPUtility29BidmadAdapterBannerAdditional_")
@protocol BidmadAdapterBannerAdditional
- (void)setBannerSize:(NSString * _Nonnull)sizeString;
- (void)hide;
@end


SWIFT_PROTOCOL("_TtP11ADOPUtility22BidmadAdapterEssential_")
@protocol BidmadAdapterEssential
@property (nonatomic, strong) id _Nullable bidmadController;
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent;
- (void)load;
- (void)show;
- (void)remove;
- (void)setIsDebug:(BOOL)isDebug;
@end

@class NSError;

SWIFT_PROTOCOL("_TtP11ADOPUtility32BidmadAdapterOfferwallAdditional_")
@protocol BidmadAdapterOfferwallAdditional
- (void)getCurrencyWithCompletionHandler:(void (^ _Nullable)(NSError * _Nullable, NSDictionary<NSString *, id> * _Nullable))completionHandler;
- (void)spendCurrency:(NSInteger)amount completionHandler:(void (^ _Nullable)(NSError * _Nullable, NSDictionary<NSString *, id> * _Nullable))completionHandler;
@end


SWIFT_PROTOCOL("_TtP11ADOPUtility29BidmadAdapterRewardAdditional_")
@protocol BidmadAdapterRewardAdditional
- (void)setIsRewardedAd:(BOOL)isRewardedAd;
@end

@class UIImage;
@class NSDecimalNumber;

SWIFT_PROTOCOL("_TtP11ADOPUtility27BidmadNativeAdDataInterface_")
@protocol BidmadNativeAdDataInterface
- (nonnull instancetype)initWithIdentifier:(NSInteger)identifier;
@property (nonatomic, copy) NSString * _Nullable headline;
@property (nonatomic, copy) NSString * _Nullable body;
@property (nonatomic, copy) NSString * _Nullable callToAction;
@property (nonatomic, strong) UIImage * _Nullable icon;
@property (nonatomic, strong) NSDecimalNumber * _Nullable starRating;
@property (nonatomic, copy) NSString * _Nullable store;
@property (nonatomic, copy) NSString * _Nullable price;
@property (nonatomic, copy) NSString * _Nullable advertiser;
@property (nonatomic, strong) id _Nullable nativeAdAdMob;
@property (nonatomic, strong) id _Nullable nativeAdPangle;
@property (nonatomic, copy) NSString * _Nullable pangleMediaImageURL;
@property (nonatomic, strong) UIView * _Nullable pangleMediaVideoView;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)remove;
@end

@class NSString;

SWIFT_CLASS("_TtC11ADOPUtility21BidmadTestEnvironment")
@interface BidmadTestEnvironment : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL testMode;)
+ (BOOL)testMode SWIFT_WARN_UNUSED_RESULT;
+ (void)setTestMode:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSString * _Nullable testOverrideJSON;)
+ (NSString * _Nullable)testOverrideJSON SWIFT_WARN_UNUSED_RESULT;
+ (void)setTestOverrideJSON:(NSString * _Nullable)value;
+ (void)displayText:(NSString * _Nonnull)text bottomPosition:(BOOL)bottomPosition;
+ (UIViewController * _Nullable)topViewControllerWithBase:(UIViewController * _Nullable)base SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestADOPRewardVideoForSuccessCase SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestADOPRewardVideoForFailCase SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestRewardVideoForSuccessCase SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestInterstitialForSuccessCase SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestInterstitialForFailCase SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestBannerForSuccessCase SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestBannerForFailCase SWIFT_WARN_UNUSED_RESULT;
+ (NSData * _Nonnull)getTestBannerForSuccessCase_RAW SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
