// Generated by Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
#ifndef BIDMADADAPTERFC_SWIFT_H
#define BIDMADADAPTERFC_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AdColony;
@import AppLovinSDK;
@import ObjectiveC;
@import UnityAds;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BidmadAdapterFC",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIViewController;
@class UIView;
@class NSNumber;

SWIFT_CLASS("_TtC15BidmadAdapterFC26BidmadAdapterFCAdEssential")
@interface BidmadAdapterFCAdEssential : NSObject
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
- (void)setBidmadController:(id _Nonnull)bidmadController;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15BidmadAdapterFC20BidmadAdColonyBanner")
@interface BidmadAdColonyBanner : BidmadAdapterFCAdEssential
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
@end


@class AdColonyAdView;
@class AdColonyAdRequestError;

@interface BidmadAdColonyBanner (SWIFT_EXTENSION(BidmadAdapterFC)) <AdColonyAdViewDelegate>
- (void)adColonyAdViewDidLoad:(AdColonyAdView * _Nonnull)adView;
- (void)adColonyAdViewDidFailToLoad:(AdColonyAdRequestError * _Nonnull)error;
- (void)adColonyAdViewDidReceiveClick:(AdColonyAdView * _Nonnull)adView;
@end


@interface BidmadAdColonyBanner (SWIFT_EXTENSION(BidmadAdapterFC))
- (void)load;
- (void)setIsDebug:(BOOL)isDebug;
- (void)setBannerSize:(NSString * _Nonnull)sizeString;
- (void)show;
- (void)hide;
- (void)remove;
@end


/// AdColony has ONE CLASS for both INTERSTITIAL and REWARD
SWIFT_CLASS("_TtC15BidmadAdapterFC26BidmadAdColonyInterstitial")
@interface BidmadAdColonyInterstitial : BidmadAdapterFCAdEssential
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
@end


@interface BidmadAdColonyInterstitial (SWIFT_EXTENSION(BidmadAdapterFC))
- (void)load;
- (void)setIsDebug:(BOOL)isDebug;
- (void)setIsRewardedAd:(BOOL)isRewardedAd;
- (void)show;
- (void)remove;
@end

@class AdColonyInterstitial;

@interface BidmadAdColonyInterstitial (SWIFT_EXTENSION(BidmadAdapterFC)) <AdColonyInterstitialDelegate>
- (void)adColonyInterstitialDidLoad:(AdColonyInterstitial * _Nonnull)interstitial;
- (void)adColonyInterstitialDidFailToLoad:(AdColonyAdRequestError * _Nonnull)error;
- (void)adColonyInterstitialExpired:(AdColonyInterstitial * _Nonnull)interstitial;
- (void)adColonyInterstitialDidReceiveClick:(AdColonyInterstitial * _Nonnull)interstitial;
- (void)adColonyInterstitialWillOpen:(AdColonyInterstitial * _Nonnull)interstitial;
- (void)adColonyInterstitialDidClose:(AdColonyInterstitial * _Nonnull)interstitial;
@end



SWIFT_CLASS("_TtC15BidmadAdapterFC22BidmadAdapterFCUtility")
@interface BidmadAdapterFCUtility : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15BidmadAdapterFC20BidmadAppLovinBanner")
@interface BidmadAppLovinBanner : BidmadAdapterFCAdEssential
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
@end

@class ALAdService;
@class ALAd;

@interface BidmadAppLovinBanner (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdLoadDelegate>
- (void)adService:(ALAdService * _Nonnull)adService didLoadAd:(ALAd * _Nonnull)ad;
- (void)adService:(ALAdService * _Nonnull)adService didFailToLoadAdWithError:(int32_t)code;
@end


@interface BidmadAppLovinBanner (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdDisplayDelegate>
- (void)ad:(ALAd * _Nonnull)ad wasDisplayedIn:(UIView * _Nonnull)view;
- (void)ad:(ALAd * _Nonnull)ad wasHiddenIn:(UIView * _Nonnull)view;
- (void)ad:(ALAd * _Nonnull)ad wasClickedIn:(UIView * _Nonnull)view;
@end

@class ALAdView;

@interface BidmadAppLovinBanner (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdViewEventDelegate>
- (void)ad:(ALAd * _Nonnull)ad didPresentFullscreenForAdView:(ALAdView * _Nonnull)adView;
- (void)ad:(ALAd * _Nonnull)ad willDismissFullscreenForAdView:(ALAdView * _Nonnull)adView;
- (void)ad:(ALAd * _Nonnull)ad didDismissFullscreenForAdView:(ALAdView * _Nonnull)adView;
- (void)ad:(ALAd * _Nonnull)ad willLeaveApplicationForAdView:(ALAdView * _Nonnull)adView;
- (void)ad:(ALAd * _Nonnull)ad didReturnToApplicationForAdView:(ALAdView * _Nonnull)adView;
- (void)ad:(ALAd * _Nonnull)ad didFailToDisplayInAdView:(ALAdView * _Nonnull)adView withError:(ALAdViewDisplayErrorCode)code;
@end


@interface BidmadAppLovinBanner (SWIFT_EXTENSION(BidmadAdapterFC))
- (void)load;
- (void)setIsDebug:(BOOL)isDebug;
- (void)setBannerSize:(NSString * _Nonnull)sizeString;
- (void)show;
- (void)hide;
- (void)remove;
@end


SWIFT_CLASS("_TtC15BidmadAdapterFC26BidmadAppLovinInterstitial")
@interface BidmadAppLovinInterstitial : BidmadAdapterFCAdEssential
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
@end


@interface BidmadAppLovinInterstitial (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdVideoPlaybackDelegate>
- (void)videoPlaybackBeganInAd:(ALAd * _Nonnull)ad;
- (void)videoPlaybackEndedInAd:(ALAd * _Nonnull)ad atPlaybackPercent:(NSNumber * _Nonnull)percentPlayed fullyWatched:(BOOL)wasFullyWatched;
@end


@interface BidmadAppLovinInterstitial (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdLoadDelegate>
- (void)adService:(ALAdService * _Nonnull)adService didLoadAd:(ALAd * _Nonnull)ad;
- (void)adService:(ALAdService * _Nonnull)adService didFailToLoadAdWithError:(int32_t)code;
@end


@interface BidmadAppLovinInterstitial (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdDisplayDelegate>
- (void)ad:(ALAd * _Nonnull)ad wasDisplayedIn:(UIView * _Nonnull)view;
- (void)ad:(ALAd * _Nonnull)ad wasHiddenIn:(UIView * _Nonnull)view;
- (void)ad:(ALAd * _Nonnull)ad wasClickedIn:(UIView * _Nonnull)view;
@end


@interface BidmadAppLovinInterstitial (SWIFT_EXTENSION(BidmadAdapterFC))
- (void)load;
- (void)setIsDebug:(BOOL)isDebug;
- (void)show;
- (void)remove;
@end


SWIFT_CLASS("_TtC15BidmadAdapterFC20BidmadAppLovinReward")
@interface BidmadAppLovinReward : BidmadAdapterFCAdEssential
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
@end


@interface BidmadAppLovinReward (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdLoadDelegate>
- (void)adService:(ALAdService * _Nonnull)adService didLoadAd:(ALAd * _Nonnull)ad;
- (void)adService:(ALAdService * _Nonnull)adService didFailToLoadAdWithError:(int32_t)code;
@end


@interface BidmadAppLovinReward (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdVideoPlaybackDelegate>
- (void)videoPlaybackBeganInAd:(ALAd * _Nonnull)ad;
- (void)videoPlaybackEndedInAd:(ALAd * _Nonnull)ad atPlaybackPercent:(NSNumber * _Nonnull)percentPlayed fullyWatched:(BOOL)wasFullyWatched;
@end


@interface BidmadAppLovinReward (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdDisplayDelegate>
- (void)ad:(ALAd * _Nonnull)ad wasDisplayedIn:(UIView * _Nonnull)view;
- (void)ad:(ALAd * _Nonnull)ad wasHiddenIn:(UIView * _Nonnull)view;
- (void)ad:(ALAd * _Nonnull)ad wasClickedIn:(UIView * _Nonnull)view;
@end


@interface BidmadAppLovinReward (SWIFT_EXTENSION(BidmadAdapterFC)) <ALAdRewardDelegate>
- (void)rewardValidationRequestForAd:(ALAd * _Nonnull)ad didSucceedWithResponse:(NSDictionary * _Nonnull)response;
- (void)rewardValidationRequestForAd:(ALAd * _Nonnull)ad didExceedQuotaWithResponse:(NSDictionary * _Nonnull)response;
- (void)rewardValidationRequestForAd:(ALAd * _Nonnull)ad wasRejectedWithResponse:(NSDictionary * _Nonnull)response;
- (void)rewardValidationRequestForAd:(ALAd * _Nonnull)ad didFailWithError:(NSInteger)responseCode;
@end


@interface BidmadAppLovinReward (SWIFT_EXTENSION(BidmadAdapterFC))
- (void)load;
- (void)setIsDebug:(BOOL)isDebug;
- (void)show;
- (void)remove;
- (void)setIsRewardedAd:(BOOL)isRewardedAd;
@end


SWIFT_CLASS("_TtC15BidmadAdapterFC20BidmadUnityAdsBanner")
@interface BidmadUnityAdsBanner : BidmadAdapterFCAdEssential
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
@end



@interface BidmadUnityAdsBanner (SWIFT_EXTENSION(BidmadAdapterFC)) <UnityAdsInitializationDelegate>
- (void)initializationComplete;
- (void)initializationFailed:(UnityAdsInitializationError)error withMessage:(NSString * _Nonnull)message;
@end

@class UADSBannerView;
@class UADSBannerError;

@interface BidmadUnityAdsBanner (SWIFT_EXTENSION(BidmadAdapterFC)) <UADSBannerViewDelegate>
- (void)bannerViewDidLoad:(UADSBannerView * _Null_unspecified)bannerView;
- (void)bannerViewDidClick:(UADSBannerView * _Null_unspecified)bannerView;
- (void)bannerViewDidLeaveApplication:(UADSBannerView * _Null_unspecified)bannerView;
- (void)bannerViewDidError:(UADSBannerView * _Null_unspecified)bannerView error:(UADSBannerError * _Null_unspecified)error;
@end


@interface BidmadUnityAdsBanner (SWIFT_EXTENSION(BidmadAdapterFC))
- (void)load;
- (void)setIsDebug:(BOOL)isDebug;
- (void)setBannerSize:(NSString * _Nonnull)sizeString;
- (void)show;
- (void)hide;
- (void)remove;
@end


SWIFT_CLASS("_TtC15BidmadAdapterFC26BidmadUnityAdsInterstitial")
@interface BidmadUnityAdsInterstitial : BidmadAdapterFCAdEssential
- (nonnull instancetype)initWithAppID:(NSString * _Nonnull)appID pubID:(NSString * _Nullable)pubID rootVC:(UIViewController * _Nonnull)rootVC parentView:(UIView * _Nullable)parentView isChild:(NSNumber * _Nullable)isChild isGDPRConsent:(NSNumber * _Nullable)isGDPRConsent isCCPAConsent:(NSNumber * _Nullable)isCCPAConsent OBJC_DESIGNATED_INITIALIZER;
@end


@interface BidmadUnityAdsInterstitial (SWIFT_EXTENSION(BidmadAdapterFC)) <UnityAdsLoadDelegate>
- (void)unityAdsAdLoaded:(NSString * _Nonnull)placementId;
- (void)unityAdsAdFailedToLoad:(NSString * _Nonnull)placementId withError:(UnityAdsLoadError)error withMessage:(NSString * _Nonnull)message;
@end


@interface BidmadUnityAdsInterstitial (SWIFT_EXTENSION(BidmadAdapterFC)) <UnityAdsInitializationDelegate>
- (void)initializationComplete;
- (void)initializationFailed:(UnityAdsInitializationError)error withMessage:(NSString * _Nonnull)message;
@end


@interface BidmadUnityAdsInterstitial (SWIFT_EXTENSION(BidmadAdapterFC)) <UnityAdsShowDelegate>
- (void)unityAdsShowComplete:(NSString * _Nonnull)placementId withFinishState:(UnityAdsShowCompletionState)state;
- (void)unityAdsShowFailed:(NSString * _Nonnull)placementId withError:(UnityAdsShowError)error withMessage:(NSString * _Nonnull)message;
- (void)unityAdsShowStart:(NSString * _Nonnull)placementId;
- (void)unityAdsShowClick:(NSString * _Nonnull)placementId;
@end


@interface BidmadUnityAdsInterstitial (SWIFT_EXTENSION(BidmadAdapterFC))
- (void)load;
- (void)setIsDebug:(BOOL)isDebug;
- (void)setIsRewardedAd:(BOOL)isRewardedAd;
- (void)show;
- (void)remove;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
