#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef BIDMADSDK_SWIFT_H
#define BIDMADSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Dispatch;
@import Foundation;
@import ObjectiveC;
#endif

#import <BidmadSDK/BidmadSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BidmadSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSUInteger, BIDMADAdPosition, open) {
  BIDMADAdPositionCenter = 0,
  BIDMADAdPositionTop = 1,
  BIDMADAdPositionBottom = 2,
  BIDMADAdPositionLeft = 3,
  BIDMADAdPositionRight = 4,
  BIDMADAdPositionTopLeft = 5,
  BIDMADAdPositionTopRight = 6,
  BIDMADAdPositionBottomLeft = 7,
  BIDMADAdPositionBottomRight = 8,
  BIDMADAdPositionNone = 9,
};

typedef SWIFT_ENUM(NSInteger, BIDMADBannerViewCase, open) {
  BIDMADBannerViewCaseXYCoordinateGiven = 0,
  BIDMADBannerViewCaseContainerViewGiven = 1,
  BIDMADBannerViewCaseOnlyYCoordinateGiven = 2,
  BIDMADBannerViewCaseAdPositionAnchorGiven = 3,
};

@class NSString;
@class BidmadFullscreenAdapter;
@protocol OBHCommunicationDelegate;
@class BidmadAdUnit;
@class UIViewController;
SWIFT_CLASS("_TtC9BidmadSDK18BIDMADInterstitial")
@interface BIDMADInterstitial : NSObject <BidmadFullscreenAdapterDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) BidmadFullscreenAdapter * _Nullable adapter;
@property (nonatomic) BOOL adBlockEstimation;
- (nonnull instancetype)initWithInstanceOBH:(id <OBHCommunicationDelegate> _Nonnull)instanceOBH OBJC_DESIGNATED_INITIALIZER;
- (void)selectAdUnit:(BidmadAdUnit * _Nonnull)adUnit;
- (void)showInterstitialViewOnViewController:(UIViewController * _Nonnull)viewController;
- (void)dismissedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)presentedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)failedToPresentWith:(BidmadFullscreenAdapter * _Nonnull)ad error:(NSError * _Nonnull)error;
- (void)clickedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)rewardedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)skippedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol BidmadAdapterInterfaceAccess;
@class NSTimer;
SWIFT_CLASS("_TtC9BidmadSDK8BMBaseAd")
@interface BMBaseAd : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)safeErrorMessageFrom:(NSError * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
/// Must be read/written only on <code>self.queue</code>.
@property (nonatomic) BidmadLoadStatus loadStatus;
@property (nonatomic, strong) id <BidmadAdapterInterfaceAccess> _Nullable loadedAdapter;
@property (nonatomic, copy) NSString * _Nullable testHost;
@property (nonatomic, copy) NSString * _Nullable testPath;
@property (nonatomic, strong) NSTimer * _Nullable timer;
@property (nonatomic, copy) NSString * _Nonnull zoneId;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
/// Validate preconditions before ad request. Return nil if valid, Error if not.
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
/// Called after load succeeds or all attempts fail. Subclass handles
/// delegate notification, visibility timer (banner), failure retry, etc.
/// Always invoked on the main thread by <code>BMBaseAd</code>, so subclasses do not
/// need to dispatch to main themselves.
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
/// Destroy ad and clean up.
/// Subclasses override <code>performRemove()</code> for type-specific cleanup.
- (void)remove;
/// Destroy ad and clean up, calling <code>completion</code> on the main thread when done.
/// Subclasses override <code>performRemove()</code> for type-specific cleanup.
- (void)removeWithCompletion:(void (^ _Nullable)(void))completion;
- (Class <BidmadAdapterInterfaceAccess> _Nullable)createAdapterClassFrom:(BidmadAdUnit * _Nonnull)adUnit error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nonnull)processWithError:(NSError * _Nullable)error adNetworkName:(NSString * _Nullable)adNetworkName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BidmadAppOpenAdapter;
@protocol BMAppOpenAdDelegate;
SWIFT_CLASS("_TtC9BidmadSDK11BMAppOpenAd")
@interface BMAppOpenAd : BMBaseAd <BidmadAppOpenAdapterDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadAppOpenAdapter * _Nullable appOpenAdapter;
@property (nonatomic, weak) id <BMAppOpenAdDelegate> _Nullable delegate;
@property (nonatomic) BOOL isAutoReload;
- (nonnull instancetype)initWithZoneID:(NSString * _Nonnull)zoneID;
- (void)load;
- (void)showOnViewController:(UIViewController * _Nonnull)viewController;
- (BOOL)isLoaded SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (void)presentedWith:(BidmadAppOpenAdapter * _Nonnull)ad;
- (void)failedToPresentWith:(BidmadAppOpenAdapter * _Nonnull)ad error:(NSError * _Nonnull)error;
- (void)clickedWith:(BidmadAppOpenAdapter * _Nonnull)ad;
- (void)dismissedWith:(BidmadAppOpenAdapter * _Nonnull)ad;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

@class BidmadInfo;
SWIFT_PROTOCOL("_TtP9BidmadSDK19BMAppOpenAdDelegate_")
@protocol BMAppOpenAdDelegate
@optional
- (void)onLoadAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMAppOpenAd * _Nonnull)bidmadAd error:(NSError * _Nonnull)error;
- (void)onShowAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onShowFailAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info error:(NSError * _Nonnull)error;
- (void)onClickAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onCloseAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
@end

@class BidmadBannerAdapter;
@protocol BMBannerDelegate;
@class UIView;
@class BidmadErasableView;
SWIFT_CLASS("_TtC9BidmadSDK8BMBanner")
@interface BMBanner : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadBannerAdapter * _Nullable bannerAdapter;
@property (nonatomic, weak) id <BMBannerDelegate> _Nullable delegate;
@property (nonatomic) enum BIDMADBannerViewCase bannerViewCase;
@property (nonatomic) CGPoint point;
@property (nonatomic) enum BIDMADAdPosition anchorPosition;
@property (nonatomic, weak) UIViewController * _Nullable viewController;
@property (nonatomic, weak) UIView * _Nullable view;
@property (nonatomic, strong) UIView * _Nonnull viewForGame;
@property (nonatomic) BOOL isHidden;
@property (nonatomic, strong) BidmadErasableView * _Nullable managedErasableView;
@property (nonatomic) BOOL adRefreshEnabled;
@property (nonatomic, readonly) BOOL isOnceLoadMode;
- (void)resetRefreshInterval;
- (void)setRefreshInterval:(NSUInteger)value;
/// User-initiated ad load. Matches Android’s load() entry point.
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
+ (BOOL)isViewVisibleWithTarget:(UIView * _Nonnull)targetView SWIFT_WARN_UNUSED_RESULT;
- (void)initiateVisibilityTimerWithCheckableView:(UIView * _Nonnull)checkableView;
- (void)updateViewPosition;
- (void)setAnchorPositionFor:(UIView * _Nonnull)view viewController:(UIViewController * _Nonnull)viewController size:(CGSize)size;
- (void)positionWithView:(UIView * _Nonnull)view insideSafeAreaOf:(UIViewController * _Nonnull)viewController;
+ (void)inspectInside:(UIView * _Nonnull)view completionHandler:(void (^ _Nonnull)(CGSize))completionHandler;
- (void)forceWithViewVisibility:(double)viewVisibility;
- (void)hide;
- (void)show;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

@interface BMBanner (SWIFT_EXTENSION(BidmadSDK)) <BidmadBannerAdapterDelegate>
- (void)clickedWith:(BidmadBannerAdapter * _Nonnull)ad;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK16BMBannerDelegate_")
@protocol BMBannerDelegate
@optional
- (void)onLoadAd:(BMBanner * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMBanner * _Nonnull)bidmadAd error:(NSError * _Nonnull)error;
- (void)onClickAd:(BMBanner * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
@end

SWIFT_CLASS("_TtC9BidmadSDK13BMBaseAdState")
@interface BMBaseAdState : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BMBaseAdState * _Nonnull shared;)
+ (BMBaseAdState * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull logQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull bannerQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull interstitialQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull rewardQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull nativeQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull appOpenQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull splashQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull customRenderedQueue;
- (dispatch_queue_t _Nonnull)queueFor:(BidmadAdType)adType SWIFT_WARN_UNUSED_RESULT;
@end

@class BidmadCustomRenderedAdapter;
@protocol BMCustomRenderedAdDelegate;
@class BidmadCustomRenderedAdContent;
SWIFT_CLASS("_TtC9BidmadSDK18BMCustomRenderedAd")
@interface BMCustomRenderedAd : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadCustomRenderedAdapter * _Nullable customRenderedAdapter;
@property (nonatomic, weak) id <BMCustomRenderedAdDelegate> _Nullable delegate;
@property (nonatomic, strong) BidmadCustomRenderedAdContent * _Nullable adContent;
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK26BMCustomRenderedAdDelegate_")
@protocol BMCustomRenderedAdDelegate
@optional
- (void)onLoadAd:(BMCustomRenderedAd * _Nonnull)ad content:(BidmadCustomRenderedAdContent * _Nonnull)content info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMCustomRenderedAd * _Nonnull)ad error:(NSError * _Nonnull)error;
@end

@class BidmadNativeAdapter;
@protocol BMNativeAdDelegate;
@class BIDMADNativeAdView;
SWIFT_CLASS("_TtC9BidmadSDK10BMNativeAd")
@interface BMNativeAd : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadNativeAdapter * _Nullable nativeAdapter;
@property (nonatomic, weak) id <BMNativeAdDelegate> _Nullable delegate;
@property (nonatomic, weak) BIDMADNativeAdView * _Nullable adBindView;
/// User-initiated ad load. Matches Android’s load() entry point.
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (CGSize)setAdViewController:(UIViewController * _Nonnull)adViewController adView:(BIDMADNativeAdView * _Nonnull)adView defaultSize:(CGSize)defaultSize SWIFT_WARN_UNUSED_RESULT;
- (void)setAdViewController:(UIViewController * _Nonnull)adViewController adView:(BIDMADNativeAdView * _Nonnull)adView;
- (void)removeAdView:(BIDMADNativeAdView * _Nonnull)adView;
@property (nonatomic, readonly) BOOL isLoaded;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

@interface BMNativeAd (SWIFT_EXTENSION(BidmadSDK)) <BidmadNativeAdapterDelegate>
- (void)clickedWith:(BidmadNativeAdapter * _Nonnull)ad;
- (void)videoEndedWith:(BidmadNativeAdapter * _Nonnull)ad;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK18BMNativeAdDelegate_")
@protocol BMNativeAdDelegate
@optional
- (void)onLoadAd:(BMNativeAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMNativeAd * _Nonnull)bidmadAd error:(NSError * _Nonnull)error;
- (void)onClickAd:(BMNativeAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
@end

@class BidmadSplashAdapter;
@protocol BMSplashAdDelegate;
@class BidmadSplashAdContent;
SWIFT_CLASS("_TtC9BidmadSDK10BMSplashAd")
@interface BMSplashAd : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadSplashAdapter * _Nullable splashAdapter;
@property (nonatomic, weak) id <BMSplashAdDelegate> _Nullable delegate;
@property (nonatomic, strong) BidmadSplashAdContent * _Nullable adContent;
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK18BMSplashAdDelegate_")
@protocol BMSplashAdDelegate
@optional
- (void)onLoadAd:(BMSplashAd * _Nonnull)ad content:(BidmadSplashAdContent * _Nonnull)content info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMSplashAd * _Nonnull)ad error:(NSError * _Nonnull)error;
@end

SWIFT_CLASS("_TtC9BidmadSDK16BidmadAES256Util")
@interface BidmadAES256Util : NSObject
/// Returns <code>[encryptedBase64, randomIV]</code> on success, <code>nil</code> on failure.
+ (NSArray<NSString *> * _Nullable)encrypt:(NSString * _Nonnull)plainText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK12BidmadAdUnit")
@interface BidmadAdUnit : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull supportedAdNetworks;)
+ (NSDictionary<NSString *, NSString *> * _Nonnull)supportedAdNetworks SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable adNetworkName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
@property (nonatomic, readonly, copy) NSString * _Nonnull placementId;
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger height;
@property (nonatomic, readonly) double floorPrice;
@property (nonatomic, readonly, copy) NSString * _Nonnull adNetworkId;
@property (nonatomic, readonly, copy) NSString * _Nonnull areaIndex;
@property (nonatomic, readonly, copy) NSString * _Nonnull key;
@property (nonatomic) NSInteger order;
@property (nonatomic) double maxWidth;
@property (nonatomic) double weight;
@property (nonatomic, copy) NSString * _Nonnull sessionId;
@property (nonatomic) BidmadAdType adType;
@property (nonatomic, copy) NSString * _Nonnull realZoneId;
@property (nonatomic, copy) NSString * _Nonnull requestedZoneId;
@property (nonatomic, strong) BidmadAdUnit * _Nullable next;
@property (nonatomic) CGSize requestedBannerAdSize;
@property (nonatomic) CGSize loadedBannerAdSize;
@property (nonatomic) CGSize detectedBannerAdSize;
- (nonnull instancetype)initWithAppId:(NSString * _Nonnull)appId placementId:(NSString * _Nonnull)placementId order:(NSInteger)order weight:(double)weight width:(NSInteger)width height:(NSInteger)height maxWidth:(double)maxWidth floorPrice:(double)floorPrice adNetworkId:(NSString * _Nonnull)adNetworkId areaIndex:(NSString * _Nonnull)areaIndex key:(NSString * _Nonnull)key OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface BidmadAdUnit (SWIFT_EXTENSION(BidmadSDK))
- (BidmadInfo * _Nonnull)stripToInfo SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC9BidmadSDK15BidmadConstants")
@interface BidmadConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull info_plist_appstore_id;)
+ (NSString * _Nonnull)info_plist_appstore_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull info_plist_cauly_app_code;)
+ (NSString * _Nonnull)info_plist_cauly_app_code SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK24BidmadDataParsingUtility")
@interface BidmadDataParsingUtility : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
+ (void)fetchAdUnitWithZoneId:(NSString * _Nonnull)zoneId completion:(void (^ _Nonnull)(BidmadAdUnit * _Nullable, NSError * _Nullable))completionHandler;
+ (void)fetchAdUnitWithZoneId:(NSString * _Nonnull)zoneId adType:(BidmadAdType)adType completion:(void (^ _Nonnull)(BidmadAdUnit * _Nullable, NSError * _Nullable))completionHandler;
+ (void)fetchAdUnitObjCWithZoneId:(NSString * _Nonnull)zoneId adType:(BidmadAdType)adType testHost:(NSString * _Nonnull)testHost testPath:(NSString * _Nonnull)testPath completionHandler:(void (^ _Nonnull)(BidmadAdUnit * _Nullable, NSError * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK20BidmadFullscreenCore")
@interface BidmadFullscreenCore : NSObject <BidmadFullscreenAdapterDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull zoneId;
@property (nonatomic, readonly, strong) BidmadFullscreenAdapter * _Nullable loadedAdapter;
@property (nonatomic, copy) void (^ _Nullable onClick)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onClose)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onComplete)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onSkip)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) NSString * _Nullable testHost;
@property (nonatomic, copy) NSString * _Nullable testPath;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
- (void)requestWithLoadCompletionHandler:(void (^ _Nonnull)(BidmadInfo * _Nullable, NSError * _Nullable))loadCompletionHandler adUnit:(BidmadAdUnit * _Nullable)adUnit;
- (void)showWithViewController:(UIViewController * _Nonnull)viewController showCompletionHandler:(void (^ _Nonnull)(BidmadInfo * _Nullable, NSError * _Nullable))showCompletionHandler;
- (void)dismissedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)presentedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)failedToPresentWith:(BidmadFullscreenAdapter * _Nonnull)ad error:(NSError * _Nonnull)error;
- (void)clickedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)rewardedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)skippedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK17BidmadGDPRAdapter_")
@protocol BidmadGDPRAdapter <NSObject>
- (nonnull instancetype)init;
@property (nonatomic, readonly) BOOL isConsentFormAvailable;
- (void)setDebugWithTestDeviceId:(NSString * _Nonnull)testDeviceId isTestEurope:(BOOL)isTestEurope;
- (void)requestConsentInfoUpdateWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)loadFormWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)showFormTo:(UIViewController * _Nullable)viewController completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
@property (nonatomic, readonly) BIDMAD_UMPConsentStatus consentStatus;
- (void)reset;
@end

SWIFT_CLASS("_TtC9BidmadSDK10BidmadInfo")
@interface BidmadInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull networkName;
@property (nonatomic, readonly) BidmadAdType type;
@property (nonatomic, readonly) CGSize requestedBannerSize;
@property (nonatomic, readonly) CGSize loadedBannerSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull zoneId;
@property (nonatomic, readonly) CGSize realBannerAdSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull descriptiveType;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull flutterArgs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNotificationCenter;
SWIFT_CLASS("_TtC9BidmadSDK21BidmadSDKReachability")
@interface BidmadSDKReachability : NSObject
@property (nonatomic, copy) void (^ _Nullable whenReachable)(BidmadSDKReachability * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable whenUnreachable)(BidmadSDKReachability * _Nonnull);
@property (nonatomic, readonly) BOOL reachableOnWWAN SWIFT_DEPRECATED_MSG("", "allowsCellularConnection");
/// Set to <code>false</code> to force Reachability.connection to .none when on cellular connection (default value <code>true</code>)
@property (nonatomic) BOOL allowsCellularConnection;
@property (nonatomic, strong) NSNotificationCenter * _Nonnull notificationCenter;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentReachabilityString SWIFT_DEPRECATED_MSG("", "description");
+ (BidmadSDKReachability * _Nullable)getInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface BidmadSDKReachability (SWIFT_EXTENSION(BidmadSDK))
- (BOOL)startNotifierAndReturnError:(NSError * _Nullable * _Nullable)error;
- (void)stopNotifier;
@property (nonatomic, readonly) BOOL isReachable;
@property (nonatomic, readonly) BOOL isReachableViaWWAN SWIFT_DEPRECATED_MSG("Please use `connection == .cellular`");
@property (nonatomic, readonly) BOOL isReachableViaWiFi SWIFT_DEPRECATED_MSG("Please use `connection == .wifi`");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class NSBundle;
SWIFT_CLASS("_TtC9BidmadSDK18BidmadSDKResources")
@interface BidmadSDKResources : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK18BidmadStateManager")
@interface BidmadStateManager : NSObject
+ (BOOL)checkCollapsibleRequestedPreviouslyFor:(NSString * _Nonnull)zoneId SWIFT_WARN_UNUSED_RESULT;
+ (void)setWithCollapsibleRequested:(BOOL)collapsibleRequested to:(NSString * _Nonnull)zoneId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface BidmadUtility (SWIFT_EXTENSION(BidmadSDK))
+ (BOOL)isViewVisibleWithTarget:(UIView * _Nonnull)targetView SWIFT_WARN_UNUSED_RESULT;
@end

@interface BidmadUtility (SWIFT_EXTENSION(BidmadSDK))
+ (Class _Nullable)resolveRuntimeClassWithModuleName:(NSString * _Nonnull)moduleName className:(NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef BIDMADSDK_SWIFT_H
#define BIDMADSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Dispatch;
@import Foundation;
@import ObjectiveC;
#endif

#import <BidmadSDK/BidmadSDK.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BidmadSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSUInteger, BIDMADAdPosition, open) {
  BIDMADAdPositionCenter = 0,
  BIDMADAdPositionTop = 1,
  BIDMADAdPositionBottom = 2,
  BIDMADAdPositionLeft = 3,
  BIDMADAdPositionRight = 4,
  BIDMADAdPositionTopLeft = 5,
  BIDMADAdPositionTopRight = 6,
  BIDMADAdPositionBottomLeft = 7,
  BIDMADAdPositionBottomRight = 8,
  BIDMADAdPositionNone = 9,
};

typedef SWIFT_ENUM(NSInteger, BIDMADBannerViewCase, open) {
  BIDMADBannerViewCaseXYCoordinateGiven = 0,
  BIDMADBannerViewCaseContainerViewGiven = 1,
  BIDMADBannerViewCaseOnlyYCoordinateGiven = 2,
  BIDMADBannerViewCaseAdPositionAnchorGiven = 3,
};

@class NSString;
@class BidmadFullscreenAdapter;
@protocol OBHCommunicationDelegate;
@class BidmadAdUnit;
@class UIViewController;
SWIFT_CLASS("_TtC9BidmadSDK18BIDMADInterstitial")
@interface BIDMADInterstitial : NSObject <BidmadFullscreenAdapterDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) BidmadFullscreenAdapter * _Nullable adapter;
@property (nonatomic) BOOL adBlockEstimation;
- (nonnull instancetype)initWithInstanceOBH:(id <OBHCommunicationDelegate> _Nonnull)instanceOBH OBJC_DESIGNATED_INITIALIZER;
- (void)selectAdUnit:(BidmadAdUnit * _Nonnull)adUnit;
- (void)showInterstitialViewOnViewController:(UIViewController * _Nonnull)viewController;
- (void)dismissedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)presentedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)failedToPresentWith:(BidmadFullscreenAdapter * _Nonnull)ad error:(NSError * _Nonnull)error;
- (void)clickedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)rewardedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)skippedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol BidmadAdapterInterfaceAccess;
@class NSTimer;
SWIFT_CLASS("_TtC9BidmadSDK8BMBaseAd")
@interface BMBaseAd : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)safeErrorMessageFrom:(NSError * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
/// Must be read/written only on <code>self.queue</code>.
@property (nonatomic) BidmadLoadStatus loadStatus;
@property (nonatomic, strong) id <BidmadAdapterInterfaceAccess> _Nullable loadedAdapter;
@property (nonatomic, copy) NSString * _Nullable testHost;
@property (nonatomic, copy) NSString * _Nullable testPath;
@property (nonatomic, strong) NSTimer * _Nullable timer;
@property (nonatomic, copy) NSString * _Nonnull zoneId;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
/// Validate preconditions before ad request. Return nil if valid, Error if not.
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
/// Called after load succeeds or all attempts fail. Subclass handles
/// delegate notification, visibility timer (banner), failure retry, etc.
/// Always invoked on the main thread by <code>BMBaseAd</code>, so subclasses do not
/// need to dispatch to main themselves.
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
/// Destroy ad and clean up.
/// Subclasses override <code>performRemove()</code> for type-specific cleanup.
- (void)remove;
/// Destroy ad and clean up, calling <code>completion</code> on the main thread when done.
/// Subclasses override <code>performRemove()</code> for type-specific cleanup.
- (void)removeWithCompletion:(void (^ _Nullable)(void))completion;
- (Class <BidmadAdapterInterfaceAccess> _Nullable)createAdapterClassFrom:(BidmadAdUnit * _Nonnull)adUnit error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nonnull)processWithError:(NSError * _Nullable)error adNetworkName:(NSString * _Nullable)adNetworkName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class BidmadAppOpenAdapter;
@protocol BMAppOpenAdDelegate;
SWIFT_CLASS("_TtC9BidmadSDK11BMAppOpenAd")
@interface BMAppOpenAd : BMBaseAd <BidmadAppOpenAdapterDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadAppOpenAdapter * _Nullable appOpenAdapter;
@property (nonatomic, weak) id <BMAppOpenAdDelegate> _Nullable delegate;
@property (nonatomic) BOOL isAutoReload;
- (nonnull instancetype)initWithZoneID:(NSString * _Nonnull)zoneID;
- (void)load;
- (void)showOnViewController:(UIViewController * _Nonnull)viewController;
- (BOOL)isLoaded SWIFT_WARN_UNUSED_RESULT;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (void)presentedWith:(BidmadAppOpenAdapter * _Nonnull)ad;
- (void)failedToPresentWith:(BidmadAppOpenAdapter * _Nonnull)ad error:(NSError * _Nonnull)error;
- (void)clickedWith:(BidmadAppOpenAdapter * _Nonnull)ad;
- (void)dismissedWith:(BidmadAppOpenAdapter * _Nonnull)ad;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

@class BidmadInfo;
SWIFT_PROTOCOL("_TtP9BidmadSDK19BMAppOpenAdDelegate_")
@protocol BMAppOpenAdDelegate
@optional
- (void)onLoadAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMAppOpenAd * _Nonnull)bidmadAd error:(NSError * _Nonnull)error;
- (void)onShowAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onShowFailAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info error:(NSError * _Nonnull)error;
- (void)onClickAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onCloseAd:(BMAppOpenAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
@end

@class BidmadBannerAdapter;
@protocol BMBannerDelegate;
@class UIView;
@class BidmadErasableView;
SWIFT_CLASS("_TtC9BidmadSDK8BMBanner")
@interface BMBanner : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadBannerAdapter * _Nullable bannerAdapter;
@property (nonatomic, weak) id <BMBannerDelegate> _Nullable delegate;
@property (nonatomic) enum BIDMADBannerViewCase bannerViewCase;
@property (nonatomic) CGPoint point;
@property (nonatomic) enum BIDMADAdPosition anchorPosition;
@property (nonatomic, weak) UIViewController * _Nullable viewController;
@property (nonatomic, weak) UIView * _Nullable view;
@property (nonatomic, strong) UIView * _Nonnull viewForGame;
@property (nonatomic) BOOL isHidden;
@property (nonatomic, strong) BidmadErasableView * _Nullable managedErasableView;
@property (nonatomic) BOOL adRefreshEnabled;
@property (nonatomic, readonly) BOOL isOnceLoadMode;
- (void)resetRefreshInterval;
- (void)setRefreshInterval:(NSUInteger)value;
/// User-initiated ad load. Matches Android’s load() entry point.
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
+ (BOOL)isViewVisibleWithTarget:(UIView * _Nonnull)targetView SWIFT_WARN_UNUSED_RESULT;
- (void)initiateVisibilityTimerWithCheckableView:(UIView * _Nonnull)checkableView;
- (void)updateViewPosition;
- (void)setAnchorPositionFor:(UIView * _Nonnull)view viewController:(UIViewController * _Nonnull)viewController size:(CGSize)size;
- (void)positionWithView:(UIView * _Nonnull)view insideSafeAreaOf:(UIViewController * _Nonnull)viewController;
+ (void)inspectInside:(UIView * _Nonnull)view completionHandler:(void (^ _Nonnull)(CGSize))completionHandler;
- (void)forceWithViewVisibility:(double)viewVisibility;
- (void)hide;
- (void)show;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

@interface BMBanner (SWIFT_EXTENSION(BidmadSDK)) <BidmadBannerAdapterDelegate>
- (void)clickedWith:(BidmadBannerAdapter * _Nonnull)ad;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK16BMBannerDelegate_")
@protocol BMBannerDelegate
@optional
- (void)onLoadAd:(BMBanner * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMBanner * _Nonnull)bidmadAd error:(NSError * _Nonnull)error;
- (void)onClickAd:(BMBanner * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
@end

SWIFT_CLASS("_TtC9BidmadSDK13BMBaseAdState")
@interface BMBaseAdState : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BMBaseAdState * _Nonnull shared;)
+ (BMBaseAdState * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull logQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull bannerQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull interstitialQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull rewardQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull nativeQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull appOpenQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull splashQueue;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull customRenderedQueue;
- (dispatch_queue_t _Nonnull)queueFor:(BidmadAdType)adType SWIFT_WARN_UNUSED_RESULT;
@end

@class BidmadCustomRenderedAdapter;
@protocol BMCustomRenderedAdDelegate;
@class BidmadCustomRenderedAdContent;
SWIFT_CLASS("_TtC9BidmadSDK18BMCustomRenderedAd")
@interface BMCustomRenderedAd : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadCustomRenderedAdapter * _Nullable customRenderedAdapter;
@property (nonatomic, weak) id <BMCustomRenderedAdDelegate> _Nullable delegate;
@property (nonatomic, strong) BidmadCustomRenderedAdContent * _Nullable adContent;
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK26BMCustomRenderedAdDelegate_")
@protocol BMCustomRenderedAdDelegate
@optional
- (void)onLoadAd:(BMCustomRenderedAd * _Nonnull)ad content:(BidmadCustomRenderedAdContent * _Nonnull)content info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMCustomRenderedAd * _Nonnull)ad error:(NSError * _Nonnull)error;
@end

@class BidmadNativeAdapter;
@protocol BMNativeAdDelegate;
@class BIDMADNativeAdView;
SWIFT_CLASS("_TtC9BidmadSDK10BMNativeAd")
@interface BMNativeAd : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadNativeAdapter * _Nullable nativeAdapter;
@property (nonatomic, weak) id <BMNativeAdDelegate> _Nullable delegate;
@property (nonatomic, weak) BIDMADNativeAdView * _Nullable adBindView;
/// User-initiated ad load. Matches Android’s load() entry point.
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (CGSize)setAdViewController:(UIViewController * _Nonnull)adViewController adView:(BIDMADNativeAdView * _Nonnull)adView defaultSize:(CGSize)defaultSize SWIFT_WARN_UNUSED_RESULT;
- (void)setAdViewController:(UIViewController * _Nonnull)adViewController adView:(BIDMADNativeAdView * _Nonnull)adView;
- (void)removeAdView:(BIDMADNativeAdView * _Nonnull)adView;
@property (nonatomic, readonly) BOOL isLoaded;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

@interface BMNativeAd (SWIFT_EXTENSION(BidmadSDK)) <BidmadNativeAdapterDelegate>
- (void)clickedWith:(BidmadNativeAdapter * _Nonnull)ad;
- (void)videoEndedWith:(BidmadNativeAdapter * _Nonnull)ad;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK18BMNativeAdDelegate_")
@protocol BMNativeAdDelegate
@optional
- (void)onLoadAd:(BMNativeAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMNativeAd * _Nonnull)bidmadAd error:(NSError * _Nonnull)error;
- (void)onClickAd:(BMNativeAd * _Nonnull)bidmadAd info:(BidmadInfo * _Nonnull)info;
@end

@class BidmadSplashAdapter;
@protocol BMSplashAdDelegate;
@class BidmadSplashAdContent;
SWIFT_CLASS("_TtC9BidmadSDK10BMSplashAd")
@interface BMSplashAd : BMBaseAd
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BidmadAdType adType;
@property (nonatomic, strong) BidmadSplashAdapter * _Nullable splashAdapter;
@property (nonatomic, weak) id <BMSplashAdDelegate> _Nullable delegate;
@property (nonatomic, strong) BidmadSplashAdContent * _Nullable adContent;
- (void)load;
- (NSError * _Nullable)validateRequestContextWithAdRefresh:(BOOL)adRefresh SWIFT_WARN_UNUSED_RESULT;
- (void)onAdLoadCompleteWithAdUnit:(BidmadAdUnit * _Nullable)adUnit error:(NSError * _Nullable)error;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK18BMSplashAdDelegate_")
@protocol BMSplashAdDelegate
@optional
- (void)onLoadAd:(BMSplashAd * _Nonnull)ad content:(BidmadSplashAdContent * _Nonnull)content info:(BidmadInfo * _Nonnull)info;
- (void)onLoadFailAd:(BMSplashAd * _Nonnull)ad error:(NSError * _Nonnull)error;
@end

SWIFT_CLASS("_TtC9BidmadSDK16BidmadAES256Util")
@interface BidmadAES256Util : NSObject
/// Returns <code>[encryptedBase64, randomIV]</code> on success, <code>nil</code> on failure.
+ (NSArray<NSString *> * _Nullable)encrypt:(NSString * _Nonnull)plainText SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK12BidmadAdUnit")
@interface BidmadAdUnit : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull supportedAdNetworks;)
+ (NSDictionary<NSString *, NSString *> * _Nonnull)supportedAdNetworks SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable adNetworkName;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
@property (nonatomic, readonly, copy) NSString * _Nonnull placementId;
@property (nonatomic, readonly) NSInteger width;
@property (nonatomic, readonly) NSInteger height;
@property (nonatomic, readonly) double floorPrice;
@property (nonatomic, readonly, copy) NSString * _Nonnull adNetworkId;
@property (nonatomic, readonly, copy) NSString * _Nonnull areaIndex;
@property (nonatomic, readonly, copy) NSString * _Nonnull key;
@property (nonatomic) NSInteger order;
@property (nonatomic) double maxWidth;
@property (nonatomic) double weight;
@property (nonatomic, copy) NSString * _Nonnull sessionId;
@property (nonatomic) BidmadAdType adType;
@property (nonatomic, copy) NSString * _Nonnull realZoneId;
@property (nonatomic, copy) NSString * _Nonnull requestedZoneId;
@property (nonatomic, strong) BidmadAdUnit * _Nullable next;
@property (nonatomic) CGSize requestedBannerAdSize;
@property (nonatomic) CGSize loadedBannerAdSize;
@property (nonatomic) CGSize detectedBannerAdSize;
- (nonnull instancetype)initWithAppId:(NSString * _Nonnull)appId placementId:(NSString * _Nonnull)placementId order:(NSInteger)order weight:(double)weight width:(NSInteger)width height:(NSInteger)height maxWidth:(double)maxWidth floorPrice:(double)floorPrice adNetworkId:(NSString * _Nonnull)adNetworkId areaIndex:(NSString * _Nonnull)areaIndex key:(NSString * _Nonnull)key OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface BidmadAdUnit (SWIFT_EXTENSION(BidmadSDK))
- (BidmadInfo * _Nonnull)stripToInfo SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC9BidmadSDK15BidmadConstants")
@interface BidmadConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull info_plist_appstore_id;)
+ (NSString * _Nonnull)info_plist_appstore_id SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull info_plist_cauly_app_code;)
+ (NSString * _Nonnull)info_plist_cauly_app_code SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK24BidmadDataParsingUtility")
@interface BidmadDataParsingUtility : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
+ (void)fetchAdUnitWithZoneId:(NSString * _Nonnull)zoneId completion:(void (^ _Nonnull)(BidmadAdUnit * _Nullable, NSError * _Nullable))completionHandler;
+ (void)fetchAdUnitWithZoneId:(NSString * _Nonnull)zoneId adType:(BidmadAdType)adType completion:(void (^ _Nonnull)(BidmadAdUnit * _Nullable, NSError * _Nullable))completionHandler;
+ (void)fetchAdUnitObjCWithZoneId:(NSString * _Nonnull)zoneId adType:(BidmadAdType)adType testHost:(NSString * _Nonnull)testHost testPath:(NSString * _Nonnull)testPath completionHandler:(void (^ _Nonnull)(BidmadAdUnit * _Nullable, NSError * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK20BidmadFullscreenCore")
@interface BidmadFullscreenCore : NSObject <BidmadFullscreenAdapterDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull className;)
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull zoneId;
@property (nonatomic, readonly, strong) BidmadFullscreenAdapter * _Nullable loadedAdapter;
@property (nonatomic, copy) void (^ _Nullable onClick)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onClose)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onComplete)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onSkip)(BidmadInfo * _Nonnull);
@property (nonatomic, copy) NSString * _Nullable testHost;
@property (nonatomic, copy) NSString * _Nullable testPath;
- (nonnull instancetype)initWithZoneId:(NSString * _Nonnull)zoneId OBJC_DESIGNATED_INITIALIZER;
- (void)requestWithLoadCompletionHandler:(void (^ _Nonnull)(BidmadInfo * _Nullable, NSError * _Nullable))loadCompletionHandler adUnit:(BidmadAdUnit * _Nullable)adUnit;
- (void)showWithViewController:(UIViewController * _Nonnull)viewController showCompletionHandler:(void (^ _Nonnull)(BidmadInfo * _Nullable, NSError * _Nullable))showCompletionHandler;
- (void)dismissedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)presentedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)failedToPresentWith:(BidmadFullscreenAdapter * _Nonnull)ad error:(NSError * _Nonnull)error;
- (void)clickedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)rewardedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (void)skippedWith:(BidmadFullscreenAdapter * _Nonnull)ad;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP9BidmadSDK17BidmadGDPRAdapter_")
@protocol BidmadGDPRAdapter <NSObject>
- (nonnull instancetype)init;
@property (nonatomic, readonly) BOOL isConsentFormAvailable;
- (void)setDebugWithTestDeviceId:(NSString * _Nonnull)testDeviceId isTestEurope:(BOOL)isTestEurope;
- (void)requestConsentInfoUpdateWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)loadFormWithCompletionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
- (void)showFormTo:(UIViewController * _Nullable)viewController completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
@property (nonatomic, readonly) BIDMAD_UMPConsentStatus consentStatus;
- (void)reset;
@end

SWIFT_CLASS("_TtC9BidmadSDK10BidmadInfo")
@interface BidmadInfo : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull networkName;
@property (nonatomic, readonly) BidmadAdType type;
@property (nonatomic, readonly) CGSize requestedBannerSize;
@property (nonatomic, readonly) CGSize loadedBannerSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull zoneId;
@property (nonatomic, readonly) CGSize realBannerAdSize;
@property (nonatomic, readonly, copy) NSString * _Nonnull descriptiveType;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull flutterArgs;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNotificationCenter;
SWIFT_CLASS("_TtC9BidmadSDK21BidmadSDKReachability")
@interface BidmadSDKReachability : NSObject
@property (nonatomic, copy) void (^ _Nullable whenReachable)(BidmadSDKReachability * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable whenUnreachable)(BidmadSDKReachability * _Nonnull);
@property (nonatomic, readonly) BOOL reachableOnWWAN SWIFT_DEPRECATED_MSG("", "allowsCellularConnection");
/// Set to <code>false</code> to force Reachability.connection to .none when on cellular connection (default value <code>true</code>)
@property (nonatomic) BOOL allowsCellularConnection;
@property (nonatomic, strong) NSNotificationCenter * _Nonnull notificationCenter;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentReachabilityString SWIFT_DEPRECATED_MSG("", "description");
+ (BidmadSDKReachability * _Nullable)getInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface BidmadSDKReachability (SWIFT_EXTENSION(BidmadSDK))
- (BOOL)startNotifierAndReturnError:(NSError * _Nullable * _Nullable)error;
- (void)stopNotifier;
@property (nonatomic, readonly) BOOL isReachable;
@property (nonatomic, readonly) BOOL isReachableViaWWAN SWIFT_DEPRECATED_MSG("Please use `connection == .cellular`");
@property (nonatomic, readonly) BOOL isReachableViaWiFi SWIFT_DEPRECATED_MSG("Please use `connection == .wifi`");
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end

@class NSBundle;
SWIFT_CLASS("_TtC9BidmadSDK18BidmadSDKResources")
@interface BidmadSDKResources : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC9BidmadSDK18BidmadStateManager")
@interface BidmadStateManager : NSObject
+ (BOOL)checkCollapsibleRequestedPreviouslyFor:(NSString * _Nonnull)zoneId SWIFT_WARN_UNUSED_RESULT;
+ (void)setWithCollapsibleRequested:(BOOL)collapsibleRequested to:(NSString * _Nonnull)zoneId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface BidmadUtility (SWIFT_EXTENSION(BidmadSDK))
+ (BOOL)isViewVisibleWithTarget:(UIView * _Nonnull)targetView SWIFT_WARN_UNUSED_RESULT;
@end

@interface BidmadUtility (SWIFT_EXTENSION(BidmadSDK))
+ (Class _Nullable)resolveRuntimeClassWithModuleName:(NSString * _Nonnull)moduleName className:(NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
